# Generated by Django 2.0.6 on 2018-06-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
