# Generated by Django 2.0.6 on 2018-06-22 22:59

import boards.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20180621_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='header_color',
            field=boards.fields.ColorField(default='#00FF00', max_length=18),
        ),
    ]
